version: '3'
services: 
    quarkus-tryout:
        image: ghcr.io/d-led/quarkus-tryout:master
        build:
            context: .
            dockerfile: src/main/docker/Dockerfile.native-distroless
        ports:
            - "8080:8080"
